### ISSUE TITLE
Minimum CMake version is 3.12

### ISSUE THREAD

**Issue by thenoursehorse** [krivenko/ezARPACK#2]
If trying to build with CMake versions < 3.12 there are a few issues. For reference, I have tested with CMake version 3.9.1, and the current version on Ubuntu 18.04 through `apt` is 3.10.2.

1. `cmake_policy(SET CMP0074 NEW)` in `./CMakeLists.txt` is only valid for CMake version 3.12 onwards. See https://cmake.org/cmake/help/git-stage/policy/CMP0074.html. This has to be commented out otherwise the build will fail. It also means that, e.g., `find_package(TRIQS)` won't work unless `-DTRIQS_DIR=path/to/triqs/lib/cmake/triqs/` is passed to CMake (or if `/path/to/triqs/share/triqsvar.sh` has been sourced). Same applies to the other backends.

2. Additionally, `add_library(catch2 OBJECT catch2/catch2-main.cpp)` in `./test/CMakeLists.txt` is only valid for CMake version 3.12 onwards. E.g., `target_link_libraries(${t} PRIVATE ezarpack catch2)` in `./test/raw/CMakeLists.txt` tries to link an OBJECT on the right hand side, so will not work with older versions of CMake. See the merge request here https://gitlab.kitware.com/cmake/cmake/merge_requests/1524. A simple fix is changing to  `add_library(catch2 SHARED catch2/catch2-main.cpp)` or `add_library(catch2 STATIC catch2/catch2-main.cpp)`, but I haven't checked if all tests pass.

**Comment by krivenko** [comment]
Dear @thenoursehorse,

Thank you for the detailed report! If the latest Ubuntu LTS release is shipped with CMake 3.10.2, than it is indeed the version to target. Let me check what needs to be changed in CMake scripts to restore compatibility.

**Comment by thenoursehorse** [comment]
Hi @krivenko, that builds with no problems. Thanks!

**Comment by krivenko** [comment]
Resolved via #3.
