### ISSUE TITLE
Eigen example doesn't work

### ISSUE THREAD

**Issue by pan3rock** [krivenko/ezARPACK#4]
All three tests of Eigen passed, but the eigen.example failed. The output is

```bash
Using ezARPACK version 0.8
Assertion failed: (index >= 0 && index < size()), function operator(), file /usr/local/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h, line 180.
[2]    65500 abort      ./example/eigen.example
```

Could you please check it?

**Comment by krivenko** [comment]
Hi @pan3rock,

Yes, indeed, I can see that failure, but only in the `Debug` mode. The uBlas example seems to be affected too.
Thanks for the report, I'll try to fix it.

**Comment by pan3rock** [comment]
Maybe the error is here:

At line 54 in eigen.example.cpp
```c++
      int j_max = std::min(N, i + bandwidth);
```
change to

```c++
      int j_max = std::min(N-1, i + bandwidth);
```

For previous version, when j = N, index of `from` exceed.

**Comment by krivenko** [comment]
Nice catch! I shall go ahead and fix all the examples then.
