### ISSUE TITLE
Failed test asymmetric.mpi.np4

### ISSUE THREAD

**Issue by thenoursehorse** [krivenko/ezARPACK#8]
While updating some old code, I noticed that the `solver_asymmetric.mpi.np4` test fails for backends raw, nda, boost, eigen (probably all of them) with the error:

`arpack_solver: No shifts could be applied during a cycle of the Implicitly restarted Arnoldi iteration. Try increasing ncv (currently ncv = 18)`.

My experience in the past is that some of the asymmetric and complex tests can be sensitive to different versions of arpack-ng, different compilers, different operating systems, and/or different PC configurations. So this test failing might not be very serious.

I don't use the asymmetric solvers, but in case this problem is more general and other users experience it I am reporting it here.

The test fails inside this Docker build with gcc12, but it will also fail with clang:

```Dockerfile
FROM ubuntu:22.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      cmake \
      g++-12 \
      gfortran \
      git \
      libgfortran5 \
      libblas-dev \
      liblapack-dev \
      libopenmpi-dev \
      openmpi-bin

USER root
RUN useradd -u 990 -m build
USER build

ENV SRC=/home/build/src \
    BUILD=/home/build \
    NCORES=4 \
    CC=gcc-12 CXX=g++-12

# Install arpack-ng
ARG PACKAGE=arpack-ng
RUN git clone https://github.com/opencollab/$PACKAGE --depth 1 $SRC/$PACKAGE
RUN mkdir -p $BUILD/$PACKAGE
WORKDIR $BUILD/$PACKAGE
RUN cmake $SRC/$PACKAGE -DBUILD_SHARED_LIBS=ON -DMPI=ON
RUN make -j$NCORES || make -j1 VERBOSE=1
RUN make test
USER root
RUN make install
USER build

# Test ezARPACK
ARG PACKAGE=ezARPACK
RUN git clone https://github.com/krivenko/$PACKAGE --depth 1 $SRC/$PACKAGE
RUN mkdir -p $BUILD/$PACKAGE
WORKDIR $BUILD/$PACKAGE
RUN cmake $SRC/$PACKAGE
RUN make -j$NCORES || make -j1 VERBOSE=1
RUN make test
```

**Comment by krivenko** [comment]
> My experience in the past is that some of the asymmetric and complex tests can be sensitive to different versions of arpack-ng, different compilers, different operating systems, and/or different PC configurations. So this test failing might not be very serious.

It's true, those ARPACK algorithms seem to be extremely sensitive to all involved software components.
I've spent hours trying to make the unit tests less fragile without making them run forever by carefully selecting input data and computation parameters (`ncv` in particular). Well, looks like there is still room for improvement.

> The test fails inside this Docker build with gcc12, but it will also fail with clang:

Thanks a lot for the `Dockerfile`!
I can both reproduce the failure and make it go away by using `libopenblas-dev` instead of `libblas-dev`/`liblapack-dev`.

Now it's time for another round of `ncv` tuning I guess...
